#!/bin/bash

dat_fn="toy.dat"
flux_fn="toyflux.dat"
extra_fn="toy+2000.dat"

w=0
t=600
# Display message and wait for a button-press
function pause() {
 read -s -n 1 -p "Press any key to continue . . ."
 echo ""
}

Usage ()
{
    if [ $# -gt 0 ]; then echo $@ >& 2; fi
    echo "Usage: `basename $0` [-n str] [-x] [-w #] [-t #] [datfile [knownflux [extra_fn]]]" >& 2
    echo "       Run toy model tests" >&2
    echo "    Switches" >&2
    echo "      -n: suffix for file names" >&2
    echo "      -x: no extra tests" >&2
    echo "      -w: wiggle [$w]" >&2
    echo "      -t: time limit secs [$t]" >&2
    echo "    Args" >&2
    echo "      datfile: Toy data [$dat_fn]" >&2
    echo "         flux: Reactions with known fluxes [$flux_fn]" >&2
    echo "     extra_fn: Added reactions [$extra_fn]" >&2
    echo "    " >&2
    exit 1
}

# Run a command
function run() {
    echo "$@"
    "$@" 
}

do_extra=1
fn_ext=""
while [ "${1:0:1}" = "-" ]
do
  arg="$1"
  shift
  case $arg in
      "-w")  w="$1" ; fn_ext="-w$1" ; shift ;;
      "-n")  fn_ext="-$1" ; shift ;;
      "-t")  t="$1" ; shift ;;
      "-x")  do_extra=0 ;;
      "-?")  Usage ;;
  "--help")  Usage ;;
      *) Usage "Unknown option" $arg ;;
  esac
done

if [ "$1" != "" ]
then
    dat_fn="$1"
fi
if [ "$2" != "" ]
then
    flux_fn="$2"
fi
if [ "$3" != "" ]
then
    extra_fn="$3"
fi
echo "Do gapfill to explore toy problem."
echo "Using"
echo "   dat file: $dat_fn"
echo " known flux: $flux_fn"
echo " extra data: $extra_fn"
#pause

sum_fn="sum${fn_ext}.dat"
sd_fn="sd${fn_ext}.dat"

base_sol_fn=base${fn_ext}.sol
model_sol_fn=model${fn_ext}.sol
lp_sol_fn=lp${fn_ext}.sol
ilp_sol_fn=ilp${fn_ext}.sol
lpx_sol_fn=lpx${fn_ext}.sol
ilpx_sol_fn=ilpx${fn_ext}.sol
incrx_sol_fn=incrx${fn_ext}.sol
combx_sol_fn=combx${fn_ext}.sol
incrx_best_fn=incrx${fn_ext}-

calib_dig=overlap-calib${fn_ext}.dig
extra_dig=overlap-extra${fn_ext}.dig
incr_dig=overlap-incr${fn_ext}.dig
comb_dig=overlap-comb${fn_ext}.dig

echo "----------------------------------------------" >> res

tmp="/tmp/dorun.tmp"
gawk '/^MET/ {print $2, -$3; print $2, $4}' $dat_fn > $tmp
grep -v '#' $flux_fn | kjoin - $dat_fn -j2 2 | gawk '{for (i=7;i<=NF;i+=2) {if ($i == "#") {break;} print $i, -$2 * $(i+1);}}' | cat $tmp - | sort | kstat -q -vn 1 -show sum | sort -nr -k2,2 > $sum_fn

echo "Run to get metabolite supply/demand rates for known fluxes"
run gapfill -s 1 -v CTS $dat_fn -f $flux_fn -o $base_sol_fn -g base.dig -w $w -t $t -p 8 -O res

echo "Process sol - supply/demand in $sd_fn"
run procout $dat_fn $flux_fn $base_sol_fn
mv procout.out $sd_fn

# Rerun to check sd_fn
run gapfill -s 1 -v CTS $dat_fn -f $flux_fn -sd $sd_fn -o $model_sol_fn -g model.dig -w $w -t $t -p 8 -O res

# Run LP without known fluxes - just match s/d
run gapfill -s 1 -v CTS $dat_fn -sd $sd_fn -o $lp_sol_fn -g lp.dig -w $w -t $t -p 8 -O res

# Run ILP without known fluxes to compare
run gapfill -s 1 -v INT $dat_fn -sd $sd_fn -o $ilp_sol_fn -g ilp.dig -w $w -t $t -p 8 -O res

run overlap -g $calib_dig $dat_fn $model_sol_fn $lp_sol_fn $ilp_sol_fn

if [ $do_extra == 0 ]
then
    exit
fi

# Run LP on extra data 
run gapfill -s 1 -v CTS $extra_fn -sd $sd_fn -o $lpx_sol_fn -g lpx.dig -w $w -t $t -p 8 -O res

# Run ILP on extra data 
run gapfill -s 1 -v INT $extra_fn -sd $sd_fn -o $ilpx_sol_fn -g ilpx.dig -w $w -t $t -p 8 -O res

run overlap -g $extra_dig $extra_fn $lp_sol_fn $lpx_sol_fn $ilpx_sol_fn

# Run INCR on extra data 
run gapfill -s 1 -v INCR $extra_fn -sd $sd_fn -o $incrx_sol_fn -g incrx.dig -b $incrx_best_fn -w $w -t $t -p 8 -O res

run overlap -g $incr_dig $extra_fn $lp_sol_fn ${incrx_best_fn}*.sol

# Run COMB on extra data 
run gapfill -s 1 -v COMB $extra_fn -sd $sd_fn -o $combx_sol_fn -g combx.dig -w $w -t $t -p 8 -O res

run overlap -g $comb_dig $extra_fn $lp_sol_fn $lpx_sol_fn $ilpx_sol_fn $combx_sol_fn 

echo "Done. View output with"
echo "dig $calib_dig &"
echo "dig $extra_dig &"
echo "dig $incr_dig &"
echo "dig $comb_dig &"



