#!/bin/bash
# Run a command
function run() {
    echo "$@"
    "$@" 
}
# Run a command with redirect to first arg
function run_redirect() {
    out_file=$1
    shift
    echo "$@ > $out_file"
    "$@" > $out_file
    if [ $? -ne 0 ]
    then
        pause
    fi
}
# Display message and wait for a button-press
function pause() {
 read -s -n 1 -p "Press any key to continue . . ."
 echo ""
}

out=toy.dat

if [ "$2" == "" ]
then
    echo "Usage: makedat <flux_file> <all.dat> [out.dat]"
    echo "  flux_file format: <reaction> <flux> <error> <compartment>"
    echo "    all.dat format: Our MET/REACT file with all reactions"
    echo "    "
    echo "           out.dat: output [$out]"
    exit 1
fi

flux=$1
all_dat=$2
if [ "$3" != "" ]
then
    out=$3
fi
tmp_react="/tmp/makedat1.tmp"
tmp_cmpd="/tmp/makedat2.tmp"

tmp3="/tmp/makedat3.tmp"
tmp4="/tmp/makedat4.tmp"

# Select reactions
echo "Select reactions with known flux"
getcol 1 $flux | uniq | kjoin - $all_dat -j2 2 -o2 > $tmp_react

echo "Check we know them all"
getcol 1 $flux | uniq | kjoin - $all_dat -j2 2 -o2 -r > $tmp3
if [ `wc -l < $tmp3` -gt 0 ]
then
    echo "Some reactions not known:"
    cat $tmp3
fi

# Find the reactions to maximise
gawk '$2 < 0 {print $1}' $flux > $tmp3
num_maxouts=`wc -l < $tmp3`
if [ $num_maxouts -gt 0 ]
then
    echo "Found $num_maxouts output reactions to maximise"
    for r in `cat $tmp3`
    do
        # Replace obj mult with -1 for output
        echo "  Process $r"
        gawk -v R=$r '$2 == R {$3 = -1;} {print;}' $tmp_react > $tmp4
        mv $tmp4 $tmp_react
    done
fi
# Find the (non-maximising) output reactions 
# Output reactions have obj mult 9999 by default, so need to replace with 1
gawk '$2 >= 0 && $4 == "O" {print $1}' $flux > $tmp3
num_outputs=`wc -l < $tmp3`
if [ $num_outputs -gt 0 ]
then
    echo "Found $num_outputs (non-max) output reactions"
    for r in `cat $tmp3`
    do
        # Replace obj mult with 1 for output compartment
        echo "  Process $r"
        gawk -v R=$r '$2 == R {$6 = 1;} {print;}' $tmp_react > $tmp4
        mv $tmp4 $tmp_react
    done
fi

numc=`grep COMPARTMENT $all_dat | wc -l`
first=$((numc + 3))

# Which compounds are used?
# Select used metabolites
echo "Select metabolites from known-flux reactions"
gawk -v F=$first '/^REACTION/ {for (i=F;i<NF;i+=3) {if ($i == "#") {break;} print $i;}}' $tmp_react | sort | uniq > $tmp_cmpd


echo "# Created by makedat `date`" > $out
echo "# Using makedat $flux $all_dat" >> $out
grep COMPARTMENT $all_dat >> $out

# Grab compounds
echo "Write metabolites"
grep '^MET' $all_dat | kjoin $tmp_cmpd - -j2 2 -o2 >> $out 

cat $tmp_react >> $out

echo "Done. Output in $out"
echo "Don't forget to fix glucose supply"



